Database:
  DBType: mysql
  UserName: root
  Password: root_mysql
  Host: 127.0.0.1:3307
  DBName: gorm_exec_db
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Server:
  RunMode: debug
  HttpPort: 8090
  ReadTimeout: 60
  WriteTimeout: 60
Log:
  LogFilePath: /Users/guoqingliu/temp/logs
  LogInfoFileName: info
  LogWarnFileName: warn
  LogFileExt: log
AccessLog:
  LogFilePath: /Users/guoqingliu/temp/logs
  LogFileName: access
  LogFileExt: log

